=== DanielNugent/College-Work/2nd Year/Information Management (XML)/.dtds/branchSecretaries.dtd
<!DOCTYPE branchSecretaries [
  
  <!ELEMENT branchSecretaries(branchSecretary*)>
  <!ELEMENT branchSecretary(name, email, address, employedBy)>
  <!ELEMENT name (firstname+, lastname)>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  
  <!-- Address of branch secretary -->
  <!ELEMENT address (#PCDATA)>
  
  <!-- Address either public or private -->
  <!ATTLIST isPrivate CDATA #IMPLIED 'n'>
  
  <!-- The branch the this secretary is employed by -->
  <!ELEMENT employedBy (branch)>
]>

=== DanielNugent/College-Work/2nd Year/Information Management (XML)/.xml files/branchSecretaries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branchSecretaries SYSTEM "branchSecretaries.dtd">

<branchSecretaries>
  <branchSecretary>
      <name>
        <firstname>Mary</firstname>
        <lastname>Higgard</lastname>
      </name>
      <email>maryhiggard@asti.ie</email>
      <address isPrivate = 'y'>45 Bulltuggart Road, Louth</address>
      <employedBy>Dublin South Central</employedBy>
    </branchSecretary>
    <branchSecretary>
      <name>
        <firstname>Simon</firstname>
        <lastname>Delaney</lastname>
      </name>
      <email>delsimon@asti.ie</email>
      <address isPrivate = 'y'>125 Church Road, Dublin</address>
      <employedBy>Stillorgan</employedBy>
  </branchSecretary>



</branchSecretaries>
