=== DanielNugent/College-Work/2nd Year/Information Management (XML)/.dtds/issues.dtd
<!DOCTYPE issues [
  <!ELEMENT issues (issue*)>
  <!ELEMENT issue(topic, member, date, information)>
  
  <!-- issue id for data management -->
  <!ATTLIST issue id CDATA #REQUIRED>
  
  <!-- ID of member who raised issue -->
  <!ATTLIST member id CDATA #REQUIRED>
  
  <!-- date on which the issue was filed -->
  <!ELEMENT date (day, month, year)>
  <!ELEMENT day (#PCDATA)>
  <!ELEMENT month (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  
  <!-- category of issue -->
  <!ELEMENT topic (#PCDATA)>
  
  <!-- issue status: resolved or unresolved -->
  <!ELEMENT status (#PCDATA)>
  
  <!-- School steward who reported the issue -->
  <!ELEMENT stewardTold (steward)>
  
  <!-- details about the issue -->
  <!ELEMENT information (#PCDATA)>
  
]

=== DanielNugent/College-Work/2nd Year/Information Management (XML)/.xml files/issues.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE issues SYSTEM "issues.dtd">
<issues>
  <issue id='1234'>
    <topic>Holidays</topic>
    <member id = '732442'></member>
    <date>
      <day>7</day>
      <month>September</month>
      <year>2017</year>
    </date>
    <information>Annual leave not honoured</information>
    <status>resolved</status>
  </issue>
  <issue id = '1235'>
    <topic>Job Security</topic>
    <member id = '500423'></member>
    <date>
      <day>03</day>
      <month>10</month>
      <year>2018</year>
    </date>
    <information>Threatened with firing on multiple occasions</information>
    <status>unresolved</status>
  </issue>

</issues>
