=== DanielNugent/College-Work/2nd Year/Information Management (XML)/.dtds/members.dtd
<! DOCTYPE members [
	
<!ELEMENT members (member*)>
<!ELEMENT member (name, email,address,nationality,dateOfBirth,registeredWithSchool,dateOfMembership)>
<!ATTLIST member idNumber CDATA #REQUIRED>

<!-- '+' Cardinality is used to show that each member will have
		at least one first name and at least one last name. --> 
<!ELEMENT name (firstname+, lastname+)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

<!--These elements are simple fields that will hold information
  		about the member. -->
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST address isPrivate CDATA #IMPLIED 'n'>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT dateOfBirth (day,month,year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!-- The member will be registered with a school.-->
<!ELEMENT registeredWithSchool (#PCDATA)>
<!ELEMENT dateOfMembership (day,month,year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
]>

=== DanielNugent/College-Work/2nd Year/Information Management (XML)/.xml files/members.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE members SYSTEM "members.dtd">
<members>
	<member idNumber='500423'>
		<name>
			<firstname>John</firstname>
			<lastname>Doe</lastname>
		</name>
		<email>johnDoe22@gmail.com</email>
		<address isPrivate='n'>10 cloverfield lane, nebraska, toronto</address>
		<nationality>finnish</nationality>
		<dateOfBirth>
            <day>12</day>
            <month>12</month>
            <year>1998</year>
        </dateOfBirth>
		<registeredWithSchool>St.Billys secondary</registeredWithSchool>
        <dateOfMembership>
            <day>12</day>
            <month>12</month>
            <year>1998</year>
        </dateOfMembership>
	</member>
  <member idNumber ='737562'>
      <name>
        <firstname>Ray</firstname>
        <lastname>Smith</lastname>
      </name>
      <address isPrivate = 'y'>14 Branberry Road, Dublin</address>
      <nationality>Irish</nationality>
      <dateOfBirth>
        <day>09</day>
        <month>06</month>
        <year>1984</year>
      </dateOfBirth>
      <email>johnsmith@gmail.com</email>
      <registeredWithSchool>St. Kildas NS</registeredWithSchool>
      <dateOfMembership>
        <day>09</day>
        <month>09</month>
        <year>2008</year>
      </dateOfMembership>
    </member>
    <member idNumber = '732442'>
      <name>
       <firstname>Joe</firstname>
       <lastname>Bloggs</lastname>
      </name>
      <address isPrivate = 'y'>123 Seasame Street, Dublin</address>
      <nationality>Moroccan</nationality>
      <dateOfBirth>
        <day>19</day>
        <month>07</month>
        <year>1967</year>
      </dateOfBirth>
      <email>joebloggs@gmail.com</email>
      <registeredWithSchool>St. Gretas NS</registeredWithSchool>
      <dateOfMembership>
        <day>20</day>
        <month>08</month>
        <year>2002</year>
      </dateOfMembership>
    </member>
</members>
